# Generated by Django 3.0.8 on 2025-03-25 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_profile_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('website', models.URLField(blank=True, max_length=150, null=True)),
                ('facebook_profile', models.URLField(blank=True, max_length=150, null=True)),
                ('twitter_profile', models.URLField(blank=True, max_length=150, null=True)),
                ('youtube_channal', models.URLField(blank=True, max_length=150, null=True)),
                ('instagram_profile', models.URLField(blank=True, max_length=150, null=True)),
                ('i_o_d_s', models.BooleanField(default=True)),
                ('sex', models.CharField(blank=True, choices=[('1', 'Male 🚹'), ('2', 'Female 🚺')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=100000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('feeling', models.CharField(blank=True, max_length=12, null=True)),
                ('post_location', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
